// Mock data for analytics and posts

export const mockAnalyticsData = {
  engagementOverview: [
    { date: "Jan 1", likes: 4000, comments: 2400, shares: 1200 },
    { date: "Jan 5", likes: 3000, comments: 1398, shares: 900 },
    { date: "Jan 10", likes: 2000, comments: 9800, shares: 1800 },
    { date: "Jan 15", likes: 2780, comments: 3908, shares: 1500 },
    { date: "Jan 20", likes: 1890, comments: 4800, shares: 1700 },
    { date: "Jan 25", likes: 2390, comments: 3800, shares: 2100 },
    { date: "Jan 30", likes: 3490, comments: 4300, shares: 2500 },
  ],
  followerGrowth: [
    { date: "Jan 1", followers: 10000 },
    { date: "Jan 5", followers: 10200 },
    { date: "Jan 10", followers: 10500 },
    { date: "Jan 15", followers: 10800 },
    { date: "Jan 20", followers: 11200 },
    { date: "Jan 25", followers: 11800 },
    { date: "Jan 30", followers: 12345 },
  ],
  platformEngagement: [
    { platform: "Instagram", likes: 4000, comments: 2400, shares: 1200 },
    { platform: "Twitter", likes: 3000, comments: 1398, shares: 900 },
    { platform: "Facebook", likes: 2000, comments: 9800, shares: 1800 },
    { platform: "TikTok", likes: 2780, comments: 3908, shares: 1500 },
    { platform: "LinkedIn", likes: 1890, comments: 4800, shares: 1700 },
  ],
  followerDemographics: [
    { ageGroup: "18-24", male: 2000, female: 2400, other: 400 },
    { ageGroup: "25-34", male: 3000, female: 3500, other: 500 },
    { ageGroup: "35-44", male: 2500, female: 2200, other: 300 },
    { ageGroup: "45-54", male: 1500, female: 1200, other: 200 },
    { ageGroup: "55+", male: 1000, female: 800, other: 100 },
  ],
}

export const mockPosts = [
  {
    id: 1,
    author: {
      name: "Jane Smith",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    timestamp: "2 hours ago",
    content: "Just launched our new product! Check it out and let me know what you think. #newlaunch #excited",
    image: "/placeholder.svg?height=400&width=600",
    likes: 245,
    comments: 32,
    shares: 18,
  },
  {
    id: 2,
    author: {
      name: "John Doe",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    timestamp: "5 hours ago",
    content: "Had an amazing brainstorming session with the team today. So many great ideas coming soon!",
    likes: 187,
    comments: 24,
    shares: 7,
  },
  {
    id: 3,
    author: {
      name: "Sarah Johnson",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    timestamp: "Yesterday",
    content: "Just hit 10,000 followers! Thank you all for your support on this journey. Here's to the next milestone!",
    image: "/placeholder.svg?height=400&width=600",
    likes: 532,
    comments: 87,
    shares: 42,
  },
]

export const mockFollowers = [
  {
    id: 1,
    name: "Alex Johnson",
    username: "alexj",
    avatar: "/placeholder.svg?height=40&width=40",
    followerCount: 1245,
    following: true,
    recentlyFollowed: false,
    followedDate: "2 months ago",
  },
  {
    id: 2,
    name: "Samantha Lee",
    username: "samlee",
    avatar: "/placeholder.svg?height=40&width=40",
    followerCount: 3567,
    following: false,
    recentlyFollowed: true,
    followedDate: "2 days ago",
  },
  {
    id: 3,
    name: "Michael Chen",
    username: "mikechen",
    avatar: "/placeholder.svg?height=40&width=40",
    followerCount: 982,
    following: true,
    recentlyFollowed: false,
    followedDate: "1 month ago",
  },
  {
    id: 4,
    name: "Emily Wilson",
    username: "emwilson",
    avatar: "/placeholder.svg?height=40&width=40",
    followerCount: 5432,
    following: true,
    recentlyFollowed: false,
    followedDate: "3 months ago",
  },
  {
    id: 5,
    name: "David Kim",
    username: "dkim",
    avatar: "/placeholder.svg?height=40&width=40",
    followerCount: 2156,
    following: false,
    recentlyFollowed: true,
    followedDate: "1 week ago",
  },
  {
    id: 6,
    name: "Jessica Brown",
    username: "jessbrown",
    avatar: "/placeholder.svg?height=40&width=40",
    followerCount: 3789,
    following: true,
    recentlyFollowed: false,
    followedDate: "2 months ago",
  },
  {
    id: 7,
    name: "Ryan Martinez",
    username: "ryanm",
    avatar: "/placeholder.svg?height=40&width=40",
    followerCount: 1567,
    following: false,
    recentlyFollowed: true,
    followedDate: "3 days ago",
  },
  {
    id: 8,
    name: "Olivia Taylor",
    username: "oliviat",
    avatar: "/placeholder.svg?height=40&width=40",
    followerCount: 4231,
    following: true,
    recentlyFollowed: false,
    followedDate: "1 month ago",
  },
  {
    id: 9,
    name: "Daniel Garcia",
    username: "dgarcia",
    avatar: "/placeholder.svg?height=40&width=40",
    followerCount: 2987,
    following: false,
    recentlyFollowed: true,
    followedDate: "2 weeks ago",
  },
]

export const mockFeed = [
  {
    id: 1,
    author: {
      name: "Jane Smith",
      username: "janesmith",
      avatar: "/placeholder.svg?height=40&width=40",
      following: true,
    },
    timestamp: "2 hours ago",
    content: "Just launched our new product! Check it out and let me know what you think. #newlaunch #excited",
    image: "/placeholder.svg?height=400&width=600",
    likes: 245,
    comments: 32,
    shares: 18,
    liked: false,
    bookmarked: false,
    trending: true,
    tags: ["newlaunch", "excited", "product"],
  },
  {
    id: 2,
    author: {
      name: "Tech Insider",
      username: "techinsider",
      avatar: "/placeholder.svg?height=40&width=40",
      following: true,
    },
    timestamp: "3 hours ago",
    content:
      "Breaking: New AI breakthrough allows for more efficient natural language processing. This could revolutionize how we interact with technology. #AI #tech #innovation",
    image: "/placeholder.svg?height=400&width=600",
    likes: 1287,
    comments: 342,
    shares: 567,
    liked: true,
    bookmarked: true,
    trending: true,
    tags: ["AI", "tech", "innovation"],
  },
  {
    id: 3,
    author: {
      name: "Sarah Johnson",
      username: "sarahj",
      avatar: "/placeholder.svg?height=40&width=40",
      following: false,
    },
    timestamp: "5 hours ago",
    content: "Just hit 10,000 followers! Thank you all for your support on this journey. Here's to the next milestone!",
    likes: 532,
    comments: 87,
    shares: 42,
    liked: false,
    bookmarked: false,
    trending: false,
    tags: ["milestone", "gratitude"],
  },
  {
    id: 4,
    author: {
      name: "Marketing Tips",
      username: "marketingtips",
      avatar: "/placeholder.svg?height=40&width=40",
      following: true,
    },
    timestamp: "Yesterday",
    content:
      "5 Social Media Strategies That Actually Work in 2025:\n\n1. Focus on authentic storytelling\n2. Leverage user-generated content\n3. Optimize for voice search\n4. Use AI for personalization\n5. Embrace micro-communities\n\n#marketing #socialmedia #tips",
    likes: 876,
    comments: 124,
    shares: 345,
    liked: false,
    bookmarked: true,
    trending: true,
    tags: ["marketing", "socialmedia", "tips"],
  },
  {
    id: 5,
    author: {
      name: "John Doe",
      username: "johndoe",
      avatar: "/placeholder.svg?height=40&width=40",
      following: false,
    },
    timestamp: "Yesterday",
    content: "Had an amazing brainstorming session with the team today. So many great ideas coming soon!",
    image: "/placeholder.svg?height=400&width=600",
    likes: 187,
    comments: 24,
    shares: 7,
    liked: false,
    bookmarked: false,
    trending: false,
  },
]

export const mockUserPosts = [
  {
    id: 1,
    content:
      "Just launched our new social media dashboard! Check it out and let me know what you think. #newlaunch #excited",
    timestamp: "2 hours ago",
    likes: 245,
    comments: 32,
    shares: 18,
    views: 1245,
    image: "/placeholder.svg?height=400&width=600",
    published: true,
    performance: {
      views: [
        { date: "Today", count: 450 },
        { date: "Yesterday", count: 795 },
      ],
    },
  },
  {
    id: 2,
    content:
      "5 tips for creating engaging social media content:\n\n1. Know your audience\n2. Use high-quality visuals\n3. Keep it concise\n4. Ask questions\n5. Be authentic\n\n#socialmedia #contentcreation #tips",
    timestamp: "2 days ago",
    likes: 532,
    comments: 87,
    shares: 156,
    views: 2345,
    published: true,
    performance: {
      views: [
        { date: "Today", count: 245 },
        { date: "Yesterday", count: 567 },
        { date: "2 days ago", count: 1533 },
      ],
    },
  },
  {
    id: 3,
    content: "Working on a new feature for our dashboard that will revolutionize how you track engagement. Stay tuned!",
    timestamp: "1 week ago",
    likes: 187,
    comments: 24,
    shares: 7,
    views: 876,
    published: true,
    performance: {
      views: [
        { date: "Today", count: 76 },
        { date: "Yesterday", count: 123 },
        { date: "2 days ago", count: 145 },
        { date: "3 days ago", count: 167 },
        { date: "4 days ago", count: 189 },
        { date: "5 days ago", count: 176 },
      ],
    },
  },
  {
    id: 4,
    content: "Draft post about upcoming social media trends for 2025. Need to add more research and examples.",
    timestamp: "3 days ago",
    likes: 0,
    comments: 0,
    shares: 0,
    views: 0,
    published: false,
  },
  {
    id: 5,
    content:
      "Draft announcement for our upcoming webinar on social media analytics. Need to finalize date and speakers.",
    timestamp: "1 week ago",
    likes: 0,
    comments: 0,
    shares: 0,
    views: 0,
    image: "/placeholder.svg?height=400&width=600",
    published: false,
  },
]
